### ISSUE TITLE
Different time signatures missing

### ISSUE THREAD

**Issue by IceDynamix** [Quaver/Quaver#602]
There's only 4/4 available by default, making 3/4 and maybe freely editable time signatures would sync the metronome up to the song correctly.

**Comment by YaLTeR** [comment]
While there's no UI for this yet, you can specify the time signature manually in the .qua file:
```yaml
TimingPoints:
- StartTime: 74
  Bpm: 150
  Signature: 3
```
3 is 3/4, 4 (or 0) is 4/4 and so on.
